library(renv)

renv::init(bioconductor = TRUE)
renv::install("tidyverse")
renv::install("furrr")
renv::install("vroom")
renv::install("data.tree")
renv::install("igraph")
renv::install("Rcpp")
renv::install("RSQLite")
renv::install("rvcheck")
renv::install("ggfun")

renv::install("YuLab-SMU/treeio")
renv::install("YuLab-SMU/ggtree")

renv::install("bioc::GenomicRanges")
renv::install("bioc::TxDb.Hsapiens.UCSC.hg19.knownGene")
renv::install("bioc::ChIPseeker")
renv::install("bioc::org.Hs.eg.db")
renv::install("bioc::rtracklayer")
renv::install("bioc::traseR")
renv::install("bioc::VariantAnnotation")

renv::snapshot()
